### ISSUE TITLE
recognized as virus

### ISSUE THREAD

**Issue by 5nickers** [photonproject/photon#12]
The windows defender recognizes the wallet as virus as blocks it. Is there any way that you can prevent this? It happens with various mining software too.

**Comment by BlueDragon747** [comment]
its a false positive due to wallet being able to mine blocks it is considered a miner and thus get issues

either compile from source or if you trust person compiling them for you then whitelist in av program

when I have contact the companies about this if I am lucky to get a reply then its Buy a code signing cert $$$ per year -.-

going to close this as its know in whole crypto scene and worst case if you no trust then compile from source *you will probs find your own compiled software also gets flagged too ^^
